#!/bin/bash

ROOT_FOLDER=`pwd`
ROOT_FOLDER_NAME=${ROOT_FOLDER##*/}
SCRIPTS_FOLDER=${ROOT_FOLDER}/Scripts
BUILD_FOLDER=${ROOT_FOLDER}/Build
SOURCE_FOLDER=${ROOT_FOLDER}/Source
LIB_FOLDER=${SOURCE_FOLDER}/Lib
MODULES_FOLDER=${LIB_FOLDER}/Modules
ISO_FILENAME=${ROOT_FOLDER_NAME}.iso
QEMU_EMULATE='iso' # iso or kernel
MODULES=(`ls ${MODULES_FOLDER}`)

source ${SCRIPTS_FOLDER}/Clean.sh
source ${SCRIPTS_FOLDER}/Compile.sh
source ${SCRIPTS_FOLDER}/CreateISO.sh
source ${SCRIPTS_FOLDER}/EmulateOS.sh
